package notion

import "github.com/clawrise/clawrise-cli/internal/adapter"

func notionPageCreateSpec() adapter.OperationSpec {
	return adapter.OperationSpec{
		Summary: "Create a Notion page.",
		Input: adapter.InputSpec{
			Required: []string{"title", "parent"},
			Optional: []string{"title_property", "properties", "children"},
			Notes: []string{
				"When using a public integration, `parent` may be omitted for workspace-level page creation.",
				"`children` supports both shorthand top-level block fields and provider-native nested block bodies.",
				"When both shorthand and provider-native fields are present on the same block, the top-level fields take precedence.",
			},
			Sample: map[string]any{
				"title": "Project notes",
				"parent": map[string]any{
					"type": "page_id",
					"id":   "page_demo",
				},
			},
		},
		Examples: []adapter.ExampleSpec{
			{
				Title:   "Create a page with shorthand child blocks",
				Command: `clawrise notion.page.create --dry-run --json '{"title":"Project notes","parent":{"type":"page_id","id":"page_demo"},"children":[{"type":"heading_1","text":"Weekly Notes"},{"type":"paragraph","text":"Generated by Clawrise."}]}'`,
			},
			{
				Title:   "Create a page with provider-native child blocks",
				Command: `clawrise notion.page.create --dry-run --json '{"title":"Project notes","parent":{"type":"page_id","id":"page_demo"},"children":[{"type":"heading_1","heading_1":{"rich_text":[{"type":"text","text":{"content":"Weekly Notes"}}]}},{"type":"paragraph","paragraph":{"rich_text":[{"type":"text","text":{"content":"Generated by Clawrise."}}]}}]}'`,
			},
			{
				Title:   "Create a page with provider payload debug and verification",
				Command: `clawrise notion.page.create --debug-provider-payload --verify --json '{"title":"Project notes","parent":{"type":"page_id","id":"page_demo"},"children":[{"type":"paragraph","text":"Generated by Clawrise."}]}'`,
			},
		},
	}
}

func notionPageGetSpec() adapter.OperationSpec {
	return adapter.OperationSpec{
		Summary: "Get a Notion page.",
		Input: adapter.InputSpec{
			Required: []string{"page_id"},
			Sample: map[string]any{
				"page_id": "page_demo",
			},
		},
	}
}

func notionPagePropertyItemGetSpec() adapter.OperationSpec {
	return adapter.OperationSpec{
		Summary: "Get a Notion page property item and preserve provider-native structure.",
		Input: adapter.InputSpec{
			Required: []string{"page_id", "property_id"},
			Optional: []string{"page_size", "page_token"},
			Sample: map[string]any{
				"page_id":     "page_demo",
				"property_id": "prop_demo",
				"page_size":   20,
			},
		},
	}
}

func notionPageUpdateSpec() adapter.OperationSpec {
	return adapter.OperationSpec{
		Summary: "Update a Notion page's properties or archive state.",
		Input: adapter.InputSpec{
			Required: []string{"page_id"},
			Optional: []string{"title", "title_property", "properties", "archived", "icon", "cover"},
			Notes: []string{
				"`--verify` and `--debug-provider-payload` are supported for this operation.",
			},
			Sample: map[string]any{
				"page_id": "page_demo",
				"title":   "Updated project notes",
			},
		},
		Examples: []adapter.ExampleSpec{
			{
				Title:   "Update page properties",
				Command: `clawrise notion.page.update --dry-run --json '{"page_id":"page_demo","title":"Updated project notes"}'`,
			},
			{
				Title:   "Update page properties with provider payload debug and verification",
				Command: `clawrise notion.page.update --debug-provider-payload --verify --json '{"page_id":"page_demo","title":"Updated project notes"}'`,
			},
		},
	}
}

func notionPageMarkdownGetSpec() adapter.OperationSpec {
	return adapter.OperationSpec{
		Summary: "Get Notion page content as markdown.",
		Input: adapter.InputSpec{
			Required: []string{"page_id"},
			Optional: []string{"include_transcript"},
			Sample: map[string]any{
				"page_id":            "page_demo",
				"include_transcript": true,
			},
		},
	}
}

func notionPageMarkdownUpdateSpec() adapter.OperationSpec {
	return adapter.OperationSpec{
		Summary: "Update Notion page content with markdown commands.",
		Input: adapter.InputSpec{
			Required: []string{"page_id", "type"},
			Optional: []string{"update_content", "replace_content", "insert_content", "replace_content_range"},
			Notes: []string{
				"`type` selects which command payload is required.",
			},
			Sample: map[string]any{
				"page_id": "page_demo",
				"type":    "replace_content",
				"replace_content": map[string]any{
					"new_str": "# Updated title",
				},
			},
		},
	}
}
