package notion

import "github.com/clawrise/clawrise-cli/internal/adapter"

func notionPageCreateSpec() adapter.OperationSpec {
	return adapter.OperationSpec{
		Summary: "Create a Notion page.",
		Input: adapter.InputSpec{
			Required: []string{"parent"},
			Optional: []string{"title", "title_property", "properties", "children", "markdown", "template", "position", "after"},
			Notes: []string{
				"Provide `title`, `markdown`, or a provider-native `properties.title` value so the new page has a title.",
				"When using a public integration, `parent` may be omitted for workspace-level page creation.",
				"`children` supports both shorthand top-level block fields and provider-native nested block bodies.",
				"`markdown` is mutually exclusive with `children` and follows the Notion markdown page API.",
				"`template` cannot be combined with `children` or `markdown` because Notion applies template content asynchronously.",
				"`position` customizes where the child page mention is inserted when the parent is a page; `after` is a shorthand alias for `position.type=after_block`.",
				"When both shorthand and provider-native fields are present on the same block, the top-level fields take precedence.",
			},
			Sample: map[string]any{
				"parent": map[string]any{
					"type": "page_id",
					"id":   "page_demo",
				},
				"title": "Project notes",
			},
		},
		Examples: []adapter.ExampleSpec{
			{
				Title:   "Create a page with shorthand child blocks",
				Command: `clawrise notion.page.create --dry-run --json '{"title":"Project notes","parent":{"type":"page_id","id":"page_demo"},"children":[{"type":"heading_1","text":"Weekly Notes"},{"type":"paragraph","text":"Generated by Clawrise."}]}'`,
			},
			{
				Title:   "Create a child page directly from markdown",
				Command: `clawrise notion.page.create --dry-run --json '{"parent":{"type":"page_id","id":"page_demo"},"markdown":"# Weekly Notes\n\nGenerated by Clawrise.","position":{"type":"page_start"}}'`,
			},
			{
				Title:   "Create a page with provider-native child blocks",
				Command: `clawrise notion.page.create --dry-run --json '{"title":"Project notes","parent":{"type":"page_id","id":"page_demo"},"children":[{"type":"heading_1","heading_1":{"rich_text":[{"type":"text","text":{"content":"Weekly Notes"}}]}},{"type":"paragraph","paragraph":{"rich_text":[{"type":"text","text":{"content":"Generated by Clawrise."}}]}}]}'`,
			},
			{
				Title:   "Create a page with provider payload debug and verification",
				Command: `clawrise notion.page.create --debug-provider-payload --verify --json '{"title":"Project notes","parent":{"type":"page_id","id":"page_demo"},"children":[{"type":"paragraph","text":"Generated by Clawrise."}]}'`,
			},
		},
	}
}

func notionPageGetSpec() adapter.OperationSpec {
	return adapter.OperationSpec{
		Summary: "Get a Notion page.",
		Input: adapter.InputSpec{
			Required: []string{"page_id"},
			Optional: []string{"filter_properties"},
			Notes: []string{
				"`filter_properties` can limit which page properties are returned on large pages.",
			},
			Sample: map[string]any{
				"page_id":           "page_demo",
				"filter_properties": []string{"title"},
			},
		},
	}
}

func notionPagePropertyItemGetSpec() adapter.OperationSpec {
	return adapter.OperationSpec{
		Summary: "Get a Notion page property item and preserve provider-native structure.",
		Input: adapter.InputSpec{
			Required: []string{"page_id", "property_id"},
			Optional: []string{"page_size", "page_token"},
			Sample: map[string]any{
				"page_id":     "page_demo",
				"property_id": "prop_demo",
				"page_size":   20,
			},
		},
	}
}

func notionPageUpdateSpec() adapter.OperationSpec {
	return adapter.OperationSpec{
		Summary: "Update a Notion page's properties or archive state.",
		Input: adapter.InputSpec{
			Required: []string{"page_id"},
			Optional: []string{"title", "title_property", "properties", "archived", "in_trash", "is_locked", "erase_content", "template", "icon", "cover"},
			Notes: []string{
				"`in_trash` is the native field for current Notion API versions; `archived` remains accepted as a backward-compatible alias.",
				"`template` currently supports `{ \"type\": \"default\" }` or `{ \"type\": \"template_id\", \"template_id\": \"...\" }`, with optional `timezone`.",
				"`--verify` and `--debug-provider-payload` are supported for this operation.",
			},
			Sample: map[string]any{
				"page_id": "page_demo",
				"title":   "Updated project notes",
			},
		},
		Examples: []adapter.ExampleSpec{
			{
				Title:   "Update page properties",
				Command: `clawrise notion.page.update --dry-run --json '{"page_id":"page_demo","title":"Updated project notes"}'`,
			},
			{
				Title:   "Archive or trash a page",
				Command: `clawrise notion.page.update --dry-run --json '{"page_id":"page_demo","in_trash":true}'`,
			},
			{
				Title:   "Update page properties with provider payload debug and verification",
				Command: `clawrise notion.page.update --debug-provider-payload --verify --json '{"page_id":"page_demo","title":"Updated project notes"}'`,
			},
		},
	}
}

func notionPageMoveSpec() adapter.OperationSpec {
	return adapter.OperationSpec{
		Summary: "Move a Notion page to another page or data source parent.",
		Input: adapter.InputSpec{
			Required: []string{"page_id", "parent"},
			Notes: []string{
				"`parent.type` must be `page_id` or `data_source_id`.",
				"This endpoint only moves regular pages; databases and other block types cannot be moved with it.",
			},
			Sample: map[string]any{
				"page_id": "page_demo",
				"parent": map[string]any{
					"type": "page_id",
					"id":   "page_parent_demo",
				},
			},
		},
		Examples: []adapter.ExampleSpec{
			{
				Title:   "Move a page under another page",
				Command: `clawrise notion.page.move --json '{"page_id":"page_demo","parent":{"type":"page_id","id":"page_parent_demo"}}'`,
			},
			{
				Title:   "Move a page into a data source",
				Command: `clawrise notion.page.move --json '{"page_id":"page_demo","parent":{"type":"data_source_id","id":"ds_demo"}}'`,
			},
		},
	}
}

func notionPageMarkdownGetSpec() adapter.OperationSpec {
	return adapter.OperationSpec{
		Summary: "Get Notion page content as markdown.",
		Input: adapter.InputSpec{
			Required: []string{"page_id"},
			Optional: []string{"include_transcript"},
			Sample: map[string]any{
				"page_id":            "page_demo",
				"include_transcript": true,
			},
		},
	}
}

func notionPageMarkdownUpdateSpec() adapter.OperationSpec {
	return adapter.OperationSpec{
		Summary: "Update Notion page content with markdown commands.",
		Input: adapter.InputSpec{
			Required: []string{"page_id", "type"},
			Optional: []string{"update_content", "replace_content", "insert_content", "replace_content_range"},
			Notes: []string{
				"`type` selects which command payload is required.",
			},
			Sample: map[string]any{
				"page_id": "page_demo",
				"type":    "replace_content",
				"replace_content": map[string]any{
					"new_str": "# Updated title",
				},
			},
		},
	}
}
