package notion

import (
	"testing"

	"github.com/clawrise/clawrise-cli/internal/adapter"
)

func TestRegisterOperationsRegistersAllNotionOperations(t *testing.T) {
	// 这个测试顺带覆盖 operation spec 和注册元数据，避免 capability 列表无声漂移。
	// This test also covers operation specs and registration metadata so capability listings do not drift silently.
	registry := adapter.NewRegistry()
	RegisterOperations(registry, newTestClient(t, nil))

	definitions := registry.Definitions()
	if len(definitions) != 46 {
		t.Fatalf("unexpected definition count: %d", len(definitions))
	}

	getDatabase, ok := registry.Resolve("notion.database.get")
	if !ok {
		t.Fatal("expected notion.database.get to be registered")
	}
	if getDatabase.Mutating {
		t.Fatalf("expected notion.database.get to be read-only: %+v", getDatabase)
	}
	if getDatabase.Spec.Summary == "" {
		t.Fatalf("expected notion.database.get summary to be present: %+v", getDatabase.Spec)
	}

	createPage, ok := registry.Resolve("notion.page.create")
	if !ok {
		t.Fatal("expected notion.page.create to be registered")
	}
	if !createPage.Mutating {
		t.Fatalf("expected notion.page.create to be mutating: %+v", createPage)
	}
	if !createPage.Spec.DryRunSupported {
		t.Fatalf("expected notion.page.create dry-run support to be enabled: %+v", createPage.Spec)
	}
	if !createPage.Spec.Idempotency.Required || !createPage.Spec.Idempotency.AutoGenerated {
		t.Fatalf("unexpected idempotency spec: %+v", createPage.Spec.Idempotency)
	}
	if len(createPage.Spec.Input.Required) != 1 {
		t.Fatalf("unexpected create page required inputs: %+v", createPage.Spec.Input.Required)
	}

	movePage, ok := registry.Resolve("notion.page.move")
	if !ok {
		t.Fatal("expected notion.page.move to be registered")
	}
	if !movePage.Mutating {
		t.Fatalf("expected notion.page.move to be mutating: %+v", movePage)
	}
	if movePage.Spec.Summary == "" {
		t.Fatalf("expected notion.page.move summary to be present: %+v", movePage.Spec)
	}

	upsertRow, ok := registry.Resolve("notion.task.data_source.row.upsert")
	if !ok {
		t.Fatal("expected notion.task.data_source.row.upsert to be registered")
	}
	if !upsertRow.Mutating {
		t.Fatalf("expected notion.task.data_source.row.upsert to be mutating: %+v", upsertRow)
	}
	if upsertRow.Spec.Summary == "" {
		t.Fatalf("expected notion.task.data_source.row.upsert summary to be present: %+v", upsertRow.Spec)
	}

	schemaEnsure, ok := registry.Resolve("notion.task.data_source.schema.ensure")
	if !ok {
		t.Fatal("expected notion.task.data_source.schema.ensure to be registered")
	}
	if !schemaEnsure.Mutating {
		t.Fatalf("expected notion.task.data_source.schema.ensure to be mutating: %+v", schemaEnsure)
	}

	upsertMarkdownChild, ok := registry.Resolve("notion.task.page.upsert_markdown_child")
	if !ok {
		t.Fatal("expected notion.task.page.upsert_markdown_child to be registered")
	}
	if !upsertMarkdownChild.Mutating {
		t.Fatalf("expected notion.task.page.upsert_markdown_child to be mutating: %+v", upsertMarkdownChild)
	}
	if upsertMarkdownChild.Spec.Summary == "" {
		t.Fatalf("expected notion.task.page.upsert_markdown_child summary to be present: %+v", upsertMarkdownChild.Spec)
	}

	patchSection, ok := registry.Resolve("notion.task.page.patch_section")
	if !ok {
		t.Fatal("expected notion.task.page.patch_section to be registered")
	}
	if !patchSection.Mutating {
		t.Fatalf("expected notion.task.page.patch_section to be mutating: %+v", patchSection)
	}
	if patchSection.Spec.Summary == "" {
		t.Fatalf("expected notion.task.page.patch_section summary to be present: %+v", patchSection.Spec)
	}

	ensureSections, ok := registry.Resolve("notion.task.page.ensure_sections")
	if !ok {
		t.Fatal("expected notion.task.page.ensure_sections to be registered")
	}
	if !ensureSections.Mutating {
		t.Fatalf("expected notion.task.page.ensure_sections to be mutating: %+v", ensureSections)
	}

	appendUnderHeading, ok := registry.Resolve("notion.task.page.append_under_heading")
	if !ok {
		t.Fatal("expected notion.task.page.append_under_heading to be registered")
	}
	if !appendUnderHeading.Mutating {
		t.Fatalf("expected notion.task.page.append_under_heading to be mutating: %+v", appendUnderHeading)
	}

	findOrCreateByPath, ok := registry.Resolve("notion.task.page.find_or_create_by_path")
	if !ok {
		t.Fatal("expected notion.task.page.find_or_create_by_path to be registered")
	}
	if !findOrCreateByPath.Mutating {
		t.Fatalf("expected notion.task.page.find_or_create_by_path to be mutating: %+v", findOrCreateByPath)
	}

	readCompletePage, ok := registry.Resolve("notion.task.page.read_complete")
	if !ok {
		t.Fatal("expected notion.task.page.read_complete to be registered")
	}
	if readCompletePage.Mutating {
		t.Fatalf("expected notion.task.page.read_complete to be read-only: %+v", readCompletePage)
	}
	if readCompletePage.Spec.Summary == "" {
		t.Fatalf("expected notion.task.page.read_complete summary to be present: %+v", readCompletePage.Spec)
	}

	readGraph, ok := registry.Resolve("notion.task.page.read_graph")
	if !ok {
		t.Fatal("expected notion.task.page.read_graph to be registered")
	}
	if readGraph.Mutating {
		t.Fatalf("expected notion.task.page.read_graph to be read-only: %+v", readGraph)
	}

	attachFileBlock, ok := registry.Resolve("notion.task.block.attach_file")
	if !ok {
		t.Fatal("expected notion.task.block.attach_file to be registered")
	}
	if !attachFileBlock.Mutating {
		t.Fatalf("expected notion.task.block.attach_file to be mutating: %+v", attachFileBlock)
	}
	if attachFileBlock.Spec.Summary == "" {
		t.Fatalf("expected notion.task.block.attach_file summary to be present: %+v", attachFileBlock.Spec)
	}

	meetingNotesGet, ok := registry.Resolve("notion.task.meeting_notes.get")
	if !ok {
		t.Fatal("expected notion.task.meeting_notes.get to be registered")
	}
	if meetingNotesGet.Mutating {
		t.Fatalf("expected notion.task.meeting_notes.get to be read-only: %+v", meetingNotesGet)
	}
	if meetingNotesGet.Spec.Summary == "" {
		t.Fatalf("expected notion.task.meeting_notes.get summary to be present: %+v", meetingNotesGet.Spec)
	}

	resolveDatabaseTarget, ok := registry.Resolve("notion.task.database.resolve_target")
	if !ok {
		t.Fatal("expected notion.task.database.resolve_target to be registered")
	}
	if resolveDatabaseTarget.Mutating {
		t.Fatalf("expected notion.task.database.resolve_target to be read-only: %+v", resolveDatabaseTarget)
	}
	if resolveDatabaseTarget.Spec.Summary == "" {
		t.Fatalf("expected notion.task.database.resolve_target summary to be present: %+v", resolveDatabaseTarget.Spec)
	}

	searchQuery, ok := registry.Resolve("notion.search.query")
	if !ok {
		t.Fatal("expected notion.search.query to be registered")
	}
	if searchQuery.Mutating {
		t.Fatalf("expected notion.search.query to be read-only: %+v", searchQuery)
	}
	if searchQuery.Spec.Summary == "" {
		t.Fatalf("expected notion.search.query summary to be present: %+v", searchQuery.Spec)
	}

	fileUploadSend, ok := registry.Resolve("notion.file_upload.send")
	if !ok {
		t.Fatal("expected notion.file_upload.send to be registered")
	}
	if !fileUploadSend.Mutating {
		t.Fatalf("expected notion.file_upload.send to be mutating: %+v", fileUploadSend)
	}
	if fileUploadSend.Spec.Summary == "" {
		t.Fatalf("expected notion.file_upload.send summary to be present: %+v", fileUploadSend.Spec)
	}

	bulkUpsert, ok := registry.Resolve("notion.task.data_source.bulk_upsert")
	if !ok {
		t.Fatal("expected notion.task.data_source.bulk_upsert to be registered")
	}
	if !bulkUpsert.Mutating {
		t.Fatalf("expected notion.task.data_source.bulk_upsert to be mutating: %+v", bulkUpsert)
	}
	if bulkUpsert.Spec.Summary == "" {
		t.Fatalf("expected notion.task.data_source.bulk_upsert summary to be present: %+v", bulkUpsert.Spec)
	}
}
