package notion

import (
	"testing"

	"github.com/clawrise/clawrise-cli/internal/adapter"
)

func TestRegisterOperationsRegistersAllNotionOperations(t *testing.T) {
	// 这个测试顺带覆盖 operation spec 和注册元数据，避免 capability 列表无声漂移。
	registry := adapter.NewRegistry()
	RegisterOperations(registry, newTestClient(t, nil))

	definitions := registry.Definitions()
	if len(definitions) != 22 {
		t.Fatalf("unexpected definition count: %d", len(definitions))
	}

	createPage, ok := registry.Resolve("notion.page.create")
	if !ok {
		t.Fatal("expected notion.page.create to be registered")
	}
	if !createPage.Mutating {
		t.Fatalf("expected notion.page.create to be mutating: %+v", createPage)
	}
	if !createPage.Spec.DryRunSupported {
		t.Fatalf("expected notion.page.create dry-run support to be enabled: %+v", createPage.Spec)
	}
	if !createPage.Spec.Idempotency.Required || !createPage.Spec.Idempotency.AutoGenerated {
		t.Fatalf("unexpected idempotency spec: %+v", createPage.Spec.Idempotency)
	}
	if len(createPage.Spec.Input.Required) != 2 {
		t.Fatalf("unexpected create page required inputs: %+v", createPage.Spec.Input.Required)
	}

	searchQuery, ok := registry.Resolve("notion.search.query")
	if !ok {
		t.Fatal("expected notion.search.query to be registered")
	}
	if searchQuery.Mutating {
		t.Fatalf("expected notion.search.query to be read-only: %+v", searchQuery)
	}
	if searchQuery.Spec.Summary == "" {
		t.Fatalf("expected notion.search.query summary to be present: %+v", searchQuery.Spec)
	}
}
