package notion

import (
	"testing"

	"github.com/clawrise/clawrise-cli/internal/adapter"
)

func TestRegisterOperationsRegistersAllNotionOperations(t *testing.T) {
	// 这个测试顺带覆盖 operation spec 和注册元数据，避免 capability 列表无声漂移。
	// This test also covers operation specs and registration metadata so capability listings do not drift silently.
	registry := adapter.NewRegistry()
	RegisterOperations(registry, newTestClient(t, nil))

	definitions := registry.Definitions()
	if len(definitions) != 30 {
		t.Fatalf("unexpected definition count: %d", len(definitions))
	}

	createPage, ok := registry.Resolve("notion.page.create")
	if !ok {
		t.Fatal("expected notion.page.create to be registered")
	}
	if !createPage.Mutating {
		t.Fatalf("expected notion.page.create to be mutating: %+v", createPage)
	}
	if !createPage.Spec.DryRunSupported {
		t.Fatalf("expected notion.page.create dry-run support to be enabled: %+v", createPage.Spec)
	}
	if !createPage.Spec.Idempotency.Required || !createPage.Spec.Idempotency.AutoGenerated {
		t.Fatalf("unexpected idempotency spec: %+v", createPage.Spec.Idempotency)
	}
	if len(createPage.Spec.Input.Required) != 1 {
		t.Fatalf("unexpected create page required inputs: %+v", createPage.Spec.Input.Required)
	}

	upsertMarkdownChild, ok := registry.Resolve("notion.task.page.upsert_markdown_child")
	if !ok {
		t.Fatal("expected notion.task.page.upsert_markdown_child to be registered")
	}
	if !upsertMarkdownChild.Mutating {
		t.Fatalf("expected notion.task.page.upsert_markdown_child to be mutating: %+v", upsertMarkdownChild)
	}
	if upsertMarkdownChild.Spec.Summary == "" {
		t.Fatalf("expected notion.task.page.upsert_markdown_child summary to be present: %+v", upsertMarkdownChild.Spec)
	}

	searchQuery, ok := registry.Resolve("notion.search.query")
	if !ok {
		t.Fatal("expected notion.search.query to be registered")
	}
	if searchQuery.Mutating {
		t.Fatalf("expected notion.search.query to be read-only: %+v", searchQuery)
	}
	if searchQuery.Spec.Summary == "" {
		t.Fatalf("expected notion.search.query summary to be present: %+v", searchQuery.Spec)
	}

	fileUploadSend, ok := registry.Resolve("notion.file_upload.send")
	if !ok {
		t.Fatal("expected notion.file_upload.send to be registered")
	}
	if !fileUploadSend.Mutating {
		t.Fatalf("expected notion.file_upload.send to be mutating: %+v", fileUploadSend)
	}
	if fileUploadSend.Spec.Summary == "" {
		t.Fatalf("expected notion.file_upload.send summary to be present: %+v", fileUploadSend.Spec)
	}
}
