package notion

import (
	"context"
	"encoding/json"
	"net/http"
	"os"
	"path/filepath"
	"testing"
)

func TestCreatePageSupportsMarkdownAndPosition(t *testing.T) {
	t.Setenv("NOTION_ACCESS_TOKEN", "notion-token")

	client := newTestClient(t, &roundTripFunc{
		handler: func(request *http.Request) (*http.Response, error) {
			if request.URL.Path != "/v1/pages" {
				t.Fatalf("unexpected request path: %s", request.URL.Path)
			}

			var payload map[string]any
			if err := json.NewDecoder(request.Body).Decode(&payload); err != nil {
				t.Fatalf("failed to decode create page request: %v", err)
			}
			if payload["markdown"] != "# 会议纪要\n\n今天完成了联调。" {
				t.Fatalf("unexpected markdown payload: %+v", payload)
			}
			position := payload["position"].(map[string]any)
			if position["type"] != "after_block" {
				t.Fatalf("unexpected position payload: %+v", position)
			}
			afterBlock := position["after_block"].(map[string]any)
			if afterBlock["id"] != "block_demo" {
				t.Fatalf("unexpected after_block payload: %+v", afterBlock)
			}
			properties := payload["properties"].(map[string]any)
			if _, ok := properties["title"]; !ok {
				t.Fatalf("expected title property in markdown create payload: %+v", payload)
			}

			return jsonResponse(t, http.StatusOK, map[string]any{
				"id":       "page_markdown_123",
				"url":      "https://www.notion.so/page_markdown_123",
				"in_trash": false,
				"parent": map[string]any{
					"type":    "page_id",
					"page_id": "page_demo",
				},
				"properties": map[string]any{
					"title": map[string]any{
						"title": []map[string]any{
							{
								"type":       "text",
								"plain_text": "会议纪要",
								"text": map[string]any{
									"content": "会议纪要",
								},
							},
						},
					},
				},
			}), nil
		},
	})

	data, appErr := client.CreatePage(context.Background(), testStaticProfile(), map[string]any{
		"parent": map[string]any{
			"type": "page_id",
			"id":   "page_demo",
		},
		"title":    "会议纪要",
		"markdown": "# 会议纪要\n\n今天完成了联调。",
		"after":    "block_demo",
	})
	if appErr != nil {
		t.Fatalf("CreatePage returned error: %+v", appErr)
	}
	if data["page_id"] != "page_markdown_123" {
		t.Fatalf("unexpected page_id: %+v", data["page_id"])
	}
}

func TestImportMarkdownPageFromFileCreatesChildPage(t *testing.T) {
	t.Setenv("NOTION_ACCESS_TOKEN", "notion-token")

	tempDir := t.TempDir()
	filePath := filepath.Join(tempDir, "weekly.md")
	if err := os.WriteFile(filePath, []byte("# Weekly Notes\n\nGenerated by tests."), 0o644); err != nil {
		t.Fatalf("failed to write markdown file: %v", err)
	}

	client := newTestClient(t, &roundTripFunc{
		handler: func(request *http.Request) (*http.Response, error) {
			if request.URL.Path != "/v1/pages" {
				t.Fatalf("unexpected request path: %s", request.URL.Path)
			}

			var payload map[string]any
			if err := json.NewDecoder(request.Body).Decode(&payload); err != nil {
				t.Fatalf("failed to decode create page request: %v", err)
			}
			if payload["markdown"] != "# Weekly Notes\n\nGenerated by tests." {
				t.Fatalf("unexpected markdown payload: %+v", payload)
			}
			parent := payload["parent"].(map[string]any)
			if parent["page_id"] != "page_demo" {
				t.Fatalf("unexpected parent payload: %+v", parent)
			}

			return jsonResponse(t, http.StatusOK, map[string]any{
				"id":       "page_import_123",
				"url":      "https://www.notion.so/page_import_123",
				"in_trash": false,
				"parent": map[string]any{
					"type":    "page_id",
					"page_id": "page_demo",
				},
				"properties": map[string]any{
					"title": map[string]any{
						"title": []map[string]any{
							{
								"type":       "text",
								"plain_text": "Weekly Notes",
								"text": map[string]any{
									"content": "Weekly Notes",
								},
							},
						},
					},
				},
			}), nil
		},
	})

	data, appErr := client.ImportMarkdownPage(context.Background(), testStaticProfile(), map[string]any{
		"parent_page_id": "page_demo",
		"file_path":      filePath,
		"title":          "Weekly Notes",
	})
	if appErr != nil {
		t.Fatalf("ImportMarkdownPage returned error: %+v", appErr)
	}
	if data["action"] != "created" || data["page_id"] != "page_import_123" {
		t.Fatalf("unexpected import result: %+v", data)
	}
}

func TestUpsertMarkdownChildPageUpdatesExistingPage(t *testing.T) {
	t.Setenv("NOTION_ACCESS_TOKEN", "notion-token")

	client := newTestClient(t, &roundTripFunc{
		handler: func(request *http.Request) (*http.Response, error) {
			switch request.URL.Path {
			case "/v1/search":
				var payload map[string]any
				if err := json.NewDecoder(request.Body).Decode(&payload); err != nil {
					t.Fatalf("failed to decode search request: %v", err)
				}
				if payload["query"] != "日报" {
					t.Fatalf("unexpected search payload: %+v", payload)
				}
				return jsonResponse(t, http.StatusOK, map[string]any{
					"results": []map[string]any{
						{
							"object": "page",
							"id":     "page_existing_123",
							"url":    "https://www.notion.so/page_existing_123",
							"parent": map[string]any{
								"type":    "page_id",
								"page_id": "page_parent_123",
							},
							"properties": map[string]any{
								"title": map[string]any{
									"title": []map[string]any{
										{
											"type":       "text",
											"plain_text": "日报",
											"text": map[string]any{
												"content": "日报",
											},
										},
									},
								},
							},
						},
					},
					"has_more": false,
				}), nil
			case "/v1/pages/page_existing_123/markdown":
				var payload map[string]any
				if err := json.NewDecoder(request.Body).Decode(&payload); err != nil {
					t.Fatalf("failed to decode markdown update request: %v", err)
				}
				if payload["type"] != "replace_content" {
					t.Fatalf("unexpected markdown update type: %+v", payload)
				}
				replaceContent := payload["replace_content"].(map[string]any)
				if replaceContent["new_str"] != "# 日报\n\n今天推进了集成测试。" {
					t.Fatalf("unexpected replace_content payload: %+v", replaceContent)
				}
				return jsonResponse(t, http.StatusOK, map[string]any{
					"object":            "page_markdown",
					"id":                "page_existing_123",
					"markdown":          "# 日报\n\n今天推进了集成测试。",
					"truncated":         false,
					"unknown_block_ids": []string{},
				}), nil
			default:
				t.Fatalf("unexpected request path: %s", request.URL.Path)
				return nil, nil
			}
		},
	})

	data, appErr := client.UpsertMarkdownChildPage(context.Background(), testStaticProfile(), map[string]any{
		"parent_page_id": "page_parent_123",
		"title":          "日报",
		"markdown":       "# 日报\n\n今天推进了集成测试。",
	})
	if appErr != nil {
		t.Fatalf("UpsertMarkdownChildPage returned error: %+v", appErr)
	}
	if data["action"] != "updated" || data["page_id"] != "page_existing_123" {
		t.Fatalf("unexpected upsert update result: %+v", data)
	}
}

func TestUpsertMarkdownChildPageCreatesMissingPage(t *testing.T) {
	t.Setenv("NOTION_ACCESS_TOKEN", "notion-token")

	client := newTestClient(t, &roundTripFunc{
		handler: func(request *http.Request) (*http.Response, error) {
			switch request.URL.Path {
			case "/v1/search":
				return jsonResponse(t, http.StatusOK, map[string]any{
					"results":  []map[string]any{},
					"has_more": false,
				}), nil
			case "/v1/pages":
				var payload map[string]any
				if err := json.NewDecoder(request.Body).Decode(&payload); err != nil {
					t.Fatalf("failed to decode create page request: %v", err)
				}
				if payload["markdown"] != "# 周会\n\n本周完成了 API 串联。" {
					t.Fatalf("unexpected markdown payload: %+v", payload)
				}
				return jsonResponse(t, http.StatusOK, map[string]any{
					"id":       "page_created_123",
					"url":      "https://www.notion.so/page_created_123",
					"in_trash": false,
					"parent": map[string]any{
						"type":    "page_id",
						"page_id": "page_parent_123",
					},
					"properties": map[string]any{
						"title": map[string]any{
							"title": []map[string]any{
								{
									"type":       "text",
									"plain_text": "周会",
									"text": map[string]any{
										"content": "周会",
									},
								},
							},
						},
					},
				}), nil
			default:
				t.Fatalf("unexpected request path: %s", request.URL.Path)
				return nil, nil
			}
		},
	})

	data, appErr := client.UpsertMarkdownChildPage(context.Background(), testStaticProfile(), map[string]any{
		"parent_page_id": "page_parent_123",
		"title":          "周会",
		"markdown":       "# 周会\n\n本周完成了 API 串联。",
	})
	if appErr != nil {
		t.Fatalf("UpsertMarkdownChildPage returned error: %+v", appErr)
	}
	if data["action"] != "created" || data["page_id"] != "page_created_123" {
		t.Fatalf("unexpected upsert create result: %+v", data)
	}
}

func TestUpsertMarkdownChildPageRejectsAmbiguousMatches(t *testing.T) {
	t.Setenv("NOTION_ACCESS_TOKEN", "notion-token")

	client := newTestClient(t, &roundTripFunc{
		handler: func(request *http.Request) (*http.Response, error) {
			if request.URL.Path != "/v1/search" {
				t.Fatalf("unexpected request path: %s", request.URL.Path)
			}
			return jsonResponse(t, http.StatusOK, map[string]any{
				"results": []map[string]any{
					{
						"object": "page",
						"id":     "page_dup_1",
						"parent": map[string]any{
							"type":    "page_id",
							"page_id": "page_parent_123",
						},
						"properties": map[string]any{
							"title": map[string]any{
								"title": []map[string]any{
									{
										"type":       "text",
										"plain_text": "日报",
										"text": map[string]any{
											"content": "日报",
										},
									},
								},
							},
						},
					},
					{
						"object": "page",
						"id":     "page_dup_2",
						"parent": map[string]any{
							"type":    "page_id",
							"page_id": "page_parent_123",
						},
						"properties": map[string]any{
							"title": map[string]any{
								"title": []map[string]any{
									{
										"type":       "text",
										"plain_text": "日报",
										"text": map[string]any{
											"content": "日报",
										},
									},
								},
							},
						},
					},
				},
				"has_more": false,
			}), nil
		},
	})

	_, appErr := client.UpsertMarkdownChildPage(context.Background(), testStaticProfile(), map[string]any{
		"parent_page_id": "page_parent_123",
		"title":          "日报",
		"markdown":       "# 日报",
	})
	if appErr == nil {
		t.Fatal("expected UpsertMarkdownChildPage to reject ambiguous matches")
	}
	if appErr.Code != "AMBIGUOUS_TARGET" {
		t.Fatalf("unexpected error code: %s", appErr.Code)
	}
}
