package adapter

import (
	"context"
	"testing"
	"time"
)

func TestRegistryRegisterAppliesDefaultsAndSortsDefinitions(t *testing.T) {
	registry := NewRegistry()

	registry.Register(Definition{
		Operation:      "  zeta.operation.run  ",
		Platform:       "  feishu  ",
		Mutating:       true,
		DefaultTimeout: 5 * time.Second,
	})
	registry.Register(Definition{
		Operation: "alpha.operation.read",
		Platform:  "notion",
		Spec: OperationSpec{
			DryRunSupported: true,
		},
	})

	resolved, ok := registry.Resolve("zeta.operation.run")
	if !ok {
		t.Fatal("expected trimmed operation name to resolve")
	}
	if resolved.Platform != "feishu" {
		t.Fatalf("unexpected trimmed platform: %q", resolved.Platform)
	}
	if !resolved.Spec.DryRunSupported {
		t.Fatal("expected register to default dry-run support to true")
	}
	if !resolved.Spec.Idempotency.Required || !resolved.Spec.Idempotency.AutoGenerated {
		t.Fatalf("expected mutating operation to receive default idempotency spec, got %+v", resolved.Spec.Idempotency)
	}

	definitions := registry.Definitions()
	if len(definitions) != 2 {
		t.Fatalf("unexpected definitions length: %d", len(definitions))
	}
	if definitions[0].Operation != "alpha.operation.read" || definitions[1].Operation != "zeta.operation.run" {
		t.Fatalf("expected definitions to be sorted by operation name, got %#v", definitions)
	}
}

func TestRegistryRegisterPreservesExplicitIdempotencySpec(t *testing.T) {
	registry := NewRegistry()
	registry.Register(Definition{
		Operation: "feishu.doc.patch",
		Platform:  "feishu",
		Mutating:  true,
		Spec: OperationSpec{
			Idempotency: IdempotencySpec{
				Required:      true,
				AutoGenerated: false,
			},
		},
	})

	resolved, ok := registry.Resolve("feishu.doc.patch")
	if !ok {
		t.Fatal("expected definition to resolve")
	}
	if !resolved.Spec.Idempotency.Required || resolved.Spec.Idempotency.AutoGenerated {
		t.Fatalf("expected explicit idempotency spec to be preserved, got %+v", resolved.Spec.Idempotency)
	}
}

func TestAccountNameContextHelpers(t *testing.T) {
	ctx := context.Background()
	ctx = WithAccountName(ctx, "  demo-account  ")
	if got := AccountNameFromContext(ctx); got != "demo-account" {
		t.Fatalf("unexpected account name from context: %q", got)
	}

	unchanged := WithAccountName(ctx, "   ")
	if got := AccountNameFromContext(unchanged); got != "demo-account" {
		t.Fatalf("expected blank account name to keep existing context value, got %q", got)
	}

	if got := AccountNameFromContext(context.Background()); got != "" {
		t.Fatalf("expected empty context to return empty account name, got %q", got)
	}
}
