package adapter

import (
	"context"
	"sort"
	"strings"
	"time"

	"github.com/clawrise/clawrise-cli/internal/apperr"
	"github.com/clawrise/clawrise-cli/internal/config"
)

// Call describes one adapter invocation context.
type Call struct {
	ProfileName    string
	Profile        config.Profile
	Input          map[string]any
	IdempotencyKey string
}

// HandlerFunc runs one adapter operation.
type HandlerFunc func(ctx context.Context, call Call) (map[string]any, *apperr.AppError)

// InputSpec describes the currently exposed input shape for `spec`.
type InputSpec struct {
	Required []string       `json:"required,omitempty"`
	Optional []string       `json:"optional,omitempty"`
	Notes    []string       `json:"notes,omitempty"`
	Sample   map[string]any `json:"sample,omitempty"`
}

// IdempotencySpec describes idempotency behavior.
type IdempotencySpec struct {
	Required      bool `json:"required"`
	AutoGenerated bool `json:"auto_generated"`
}

// ExampleSpec describes one command example.
type ExampleSpec struct {
	Title   string `json:"title"`
	Command string `json:"command"`
}

// OperationSpec describes discovery metadata for one operation.
type OperationSpec struct {
	Summary          string          `json:"summary,omitempty"`
	Description      string          `json:"description,omitempty"`
	DryRunSupported  bool            `json:"dry_run_supported"`
	Input            InputSpec       `json:"input,omitempty"`
	Idempotency      IdempotencySpec `json:"idempotency,omitempty"`
	Examples         []ExampleSpec   `json:"examples,omitempty"`
	Stability        string          `json:"stability,omitempty"`
	UnsupportedNotes []string        `json:"unsupported_notes,omitempty"`
}

// Definition stores the base metadata for one operation.
type Definition struct {
	Operation       string
	Platform        string
	Mutating        bool
	DefaultTimeout  time.Duration
	AllowedSubjects []string
	Handler         HandlerFunc
	Spec            OperationSpec
}

// Registry manages metadata for the currently registered operations.
type Registry struct {
	definitions map[string]Definition
}

type callContextKey string

const profileNameContextKey callContextKey = "profile_name"

// NewRegistry creates an empty registry.
func NewRegistry() *Registry {
	return &Registry{
		definitions: map[string]Definition{},
	}
}

// Register stores one operation definition.
func (r *Registry) Register(def Definition) {
	def.Operation = strings.TrimSpace(def.Operation)
	def.Platform = strings.TrimSpace(def.Platform)
	if !def.Spec.DryRunSupported {
		def.Spec.DryRunSupported = true
	}
	if def.Mutating && !def.Spec.Idempotency.Required && !def.Spec.Idempotency.AutoGenerated {
		def.Spec.Idempotency = IdempotencySpec{
			Required:      true,
			AutoGenerated: true,
		}
	}
	r.definitions[def.Operation] = def
}

// Resolve looks up metadata by normalized operation name.
func (r *Registry) Resolve(operation string) (Definition, bool) {
	definition, ok := r.definitions[operation]
	return definition, ok
}

// Definitions returns all definitions sorted by operation name.
func (r *Registry) Definitions() []Definition {
	operations := make([]string, 0, len(r.definitions))
	for operation := range r.definitions {
		operations = append(operations, operation)
	}
	sort.Strings(operations)

	definitions := make([]Definition, 0, len(operations))
	for _, operation := range operations {
		definitions = append(definitions, r.definitions[operation])
	}
	return definitions
}

// WithProfileName 把当前执行的 profile 名附加到 context，供 provider auth 逻辑复用。
func WithProfileName(ctx context.Context, profileName string) context.Context {
	profileName = strings.TrimSpace(profileName)
	if profileName == "" {
		return ctx
	}
	return context.WithValue(ctx, profileNameContextKey, profileName)
}

// ProfileNameFromContext 读取当前执行上下文中的 profile 名。
func ProfileNameFromContext(ctx context.Context) string {
	if ctx == nil {
		return ""
	}
	profileName, _ := ctx.Value(profileNameContextKey).(string)
	return strings.TrimSpace(profileName)
}
